### PR TITLE
Updating activityIndicator position

### PR DESCRIPTION
**Pull request by ks-simakov**
If UIImageView changes its size, activityIndicator was still on its old
position.
I did an update that catching view resize event and updating position
of activityIndicator

### CODE REVIEW

**Comment by tonyarnold** [comment]
This fixed initial layout issues for me. Thanks, @GigabyteTheOne!

**Comment by JJSaccolo** [comment]
Thanks, will merge it! 
As a little note, I'll modify the `layoutSubviews` method, calling `[super layoutSubviews]` :)

**Comment by ks-simakov** [comment]
Great! Thanks :)

**Comment by JJSaccolo** [comment]
Pod updated (now version 1.2). Many thanks :)

**Pull request merged**
