### PR TITLE
safer calls for UIKit

### PR DESCRIPTION
**Pull request by mRs-**

### CODE REVIEW

**Comment by JJSaccolo** [comment]
Hi! 
Thanks for the PR.
Did you have problem without these changes?

**Comment by mRs-** [comment]
Absolutely. It's possible you could call the methods from a background process and all UI stuff belongs to the main thread. So this is a failsafe solution for this

**Comment by JJSaccolo** [comment]
Yep, I agree. 
Merged! 
Will update the podspec later in this afternoon.
Thank you very much :)

**Comment by mRs-** [comment]
awesome!

**Pull request merged**
