### PR TITLE
Changes to support the new SDWebImage version

### PR DESCRIPTION
**Pull request by mythodeia**
SDWebImage has been undergoing several changes and some of them had to do with method names and additions to the completionblock.
this pull request makes sure your code stays compatible with the new version
thanks

### CODE REVIEW

**Comment by taher-mosbah** [comment]
+1, you beat me to it, was just preparing a pull request :)

**Comment by VilemKurz** [comment]
+1, please merge

**Comment by JJSaccolo** [comment]
Sorry guys, I was on vacation (yeah, really long :P). 
Will do as soon as possible! 
Thank you very very much!

**Comment by JJSaccolo** [comment]
Merged, updated the podspec and pushed to the Cocoapods specs repo. 
Thanks :)

**Pull request merged**
